/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Personal Thoughts
 */
import DAO.*;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
public class fundsTransfer1 extends javax.swing.JFrame {

    /**
     * Creates new form fundsTransfer1
     */
    String cardNo;
    public fundsTransfer1(String no) {
        cardNo=no;
        icons();
        initComponents();
    }
public void icons()
     {
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("if_atm-machine_531881.png")));
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        myAccount1 = new javax.swing.JTextField();
        getterAccount1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        getAmount = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Enter your card No : ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 100, 150, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Enter receiver card No :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 150, 170, 17);
        jPanel1.add(myAccount1);
        myAccount1.setBounds(240, 90, 160, 30);
        jPanel1.add(getterAccount1);
        getterAccount1.setBounds(240, 140, 160, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Enter amount : ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 200, 130, 17);
        jPanel1.add(getAmount);
        getAmount.setBounds(240, 190, 160, 30);

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("TRANSFER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(270, 270, 100, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("TRANSFER YOUR FUND");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(110, 10, 320, 29);

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(435, 30, 80, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Delete-icon.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(530, 30, 70, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/light-blue-wallpaper-7837-8130-hd-wallpapers-1024x640.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 570, 390);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 390));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String myCard, getterCard,amountTransfer;
        if(myAccount1.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Enter your Card No:","Required Field",JOptionPane.ERROR_MESSAGE);
            return;
        }
        myCard= myAccount1.getText();
        GeneralDAO g= new GeneralDAO();
        int card1,card2;
        boolean value=g.verifyCard(myCard);
        if(value== false)
        {
            JOptionPane.showMessageDialog(null,"Enter your valid card number:","Required Field",JOptionPane.ERROR_MESSAGE);
            myAccount1.setText("");
            return;
        }
        if(getterAccount1.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Enter the receiver account number:","Required Field",JOptionPane.ERROR_MESSAGE);
            return;
        }
        getterCard= getterAccount1.getText();
        boolean value1= g.verifyCard(getterCard);
        if(value1==false)
        {
            JOptionPane.showMessageDialog(null,"Enter valid receiver Card number:","Required Field",JOptionPane.ERROR_MESSAGE);
            getterAccount1.setText("");
            return;
        }
        //card1= Integer.parseInt(myCard);
        //card2= Integer.parseInt(getterCard);
        if(myCard.equals(getterCard))
        {
            JOptionPane.showMessageDialog(null,"Invalid Card Number","Required Field",JOptionPane.ERROR_MESSAGE);
            myAccount1.setText("");
            getterAccount1.setText("");
            return;
        }
        amountTransfer= getAmount.getText();
        if(getAmount.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Enter Amount to Transfer:","Required Field",JOptionPane.ERROR_MESSAGE);
            return ;
        }
       boolean value2= g.transferFund(myCard,getterCard,amountTransfer);
       if(value2)
       {
           JOptionPane.showMessageDialog(null,"Fund Transfer Successfully:","Required Field",JOptionPane.INFORMATION_MESSAGE);
           // here set all the fields with the empty string....
           myAccount1.setText("");
           getterAccount1.setText("");
           getAmount.setText("");
           otherTransaction trans = new otherTransaction(cardNo);
           trans.setVisible(true);
           trans.setLocationRelativeTo(null);
           this.dispose();
       }
        else
       {
           JOptionPane.showMessageDialog(null,"Transaction Failed ! ..Not enough Money in your account :","Required Field",JOptionPane.ERROR_MESSAGE);
            otherTransaction trans = new otherTransaction(cardNo);
           trans.setVisible(true);
           trans.setLocationRelativeTo(null);
           this.dispose();
       }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        signin in = new signin();
        in.setVisible(true);
        in.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fundsTransfer1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fundsTransfer1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fundsTransfer1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fundsTransfer1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fundsTransfer1("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField getAmount;
    private javax.swing.JTextField getterAccount1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField myAccount1;
    // End of variables declaration//GEN-END:variables
}
