/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 8470p
 */
import DAO.*;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.util.Random;

public class signup extends javax.swing.JFrame {

    /**
     * Creates new form signup
     */
    public signup() {
        icons();
        initComponents();
    }
public void icons()
     {
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("if_atm-machine_531881.png")));
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myGroup = new javax.swing.ButtonGroup();
        myButton = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        field1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        field2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        date1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        month1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        year1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        button1 = new javax.swing.JRadioButton();
        button2 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        field3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        field5 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        field7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        button3 = new javax.swing.JRadioButton();
        button4 = new javax.swing.JRadioButton();
        cityField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        password1 = new javax.swing.JPasswordField();
        format1 = new javax.swing.JFormattedTextField();
        jButton3 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("REGISTERATION FORM");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 60, 290, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Page 1 : Personal Details");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(230, 90, 180, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Name :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 140, 80, 17);
        jPanel1.add(field1);
        field1.setBounds(190, 130, 340, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Father's Name : ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 180, 120, 20);
        jPanel1.add(field2);
        field2.setBounds(190, 180, 340, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Date Of Birth :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 340, 120, 17);

        jLabel6.setText("Date");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(180, 340, 30, 20);

        date1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(date1);
        date1.setBounds(210, 340, 56, 20);

        jLabel7.setText("Month");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(280, 340, 40, 20);

        month1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "Feburary", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        jPanel1.add(month1);
        month1.setBounds(320, 340, 100, 20);

        jLabel8.setText("Year");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(430, 340, 30, 20);

        year1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016" }));
        jPanel1.add(year1);
        year1.setBounds(460, 340, 70, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Gender :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(60, 380, 60, 17);

        myGroup.add(button1);
        button1.setText("Male");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel1.add(button1);
        button1.setBounds(260, 380, 93, 23);

        myGroup.add(button2);
        button2.setText("Female");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        jPanel1.add(button2);
        button2.setBounds(370, 380, 70, 23);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Email Address :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(50, 280, 120, 17);

        field3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field3ActionPerformed(evt);
            }
        });
        jPanel1.add(field3);
        field3.setBounds(190, 280, 340, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Martial Status :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(50, 420, 110, 17);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText(" Address : ");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(50, 600, 80, 17);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("City :");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(70, 500, 36, 20);
        jPanel1.add(field5);
        field5.setBounds(190, 550, 340, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Pin Code : ");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(50, 460, 80, 17);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("State : ");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(60, 530, 60, 60);
        jPanel1.add(field7);
        field7.setBounds(190, 600, 340, 30);

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(310, 650, 100, 31);

        myButton.add(button3);
        button3.setText("Single ");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        jPanel1.add(button3);
        button3.setBounds(260, 410, 70, 23);

        myButton.add(button4);
        button4.setText("Married");
        jPanel1.add(button4);
        button4.setBounds(370, 410, 120, 23);
        jPanel1.add(cityField);
        cityField.setBounds(190, 500, 340, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Cnic Num :");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(50, 230, 90, 17);
        jPanel1.add(password1);
        password1.setBounds(190, 450, 340, 30);

        try {
            format1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-#######-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(format1);
        format1.setBounds(190, 230, 340, 30);

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(580, 30, 73, 40);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Delete-icon.png"))); // NOI18N
        jPanel1.add(jLabel17);
        jLabel17.setBounds(660, 44, 24, 20);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void field3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field3ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_button2ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:     
    }//GEN-LAST:event_button1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (field1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter Your Name", "Automated Teller Machine", JOptionPane.ERROR_MESSAGE);
        } else if (field2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter Your Father's Name", "Automated Teller Machine", JOptionPane.ERROR_MESSAGE);
        }  else if (format1 .getText().isEmpty()) {
             JOptionPane.showMessageDialog(null, "Please Enter Your CNIC", "Automated Teller Machine", JOptionPane.ERROR_MESSAGE);
        }
        else if(field3.getText().isEmpty())
        {
            
            JOptionPane.showMessageDialog(null, "Please Enter Your Email", "Automated Teller Machine", JOptionPane.ERROR_MESSAGE);
        }
        else if (!button1.isSelected() && !button2.isSelected()) {
            JOptionPane.showMessageDialog(null, "Please Select  Your Gender", "Automated Teller Machine", JOptionPane.ERROR_MESSAGE);
        }
        else if (!button3.isSelected() && !button4.isSelected()) {
            JOptionPane.showMessageDialog(null, "Please Select  Your Martial Status", "Automated Teller Machine", JOptionPane.ERROR_MESSAGE);
        } 
        else if (password1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter Your PIN Code", "Automated Teller Machine", JOptionPane.ERROR_MESSAGE);
        }
        
        else if (cityField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter Your City", "Automated Teller Machine", JOptionPane.ERROR_MESSAGE);
        }  else if (field5.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter Your State", "Automated Teller Machine", JOptionPane.ERROR_MESSAGE);
        }
        else if(field7.getText().isEmpty())
        {
             JOptionPane.showMessageDialog(null, "Please Enter Your Address", "Automated Teller Machine", JOptionPane.ERROR_MESSAGE);
        }
        else {
            String name, f_name, email, address, pin, state, gender, status, city,date,month,year,dob;
            String cnic;
            boolean flag = false;
            boolean value = false;
            name = field1.getText();
            f_name = field2.getText();
            email = field3.getText();
            address = field7.getText();
            pin = password1.getText();
            state = field5.getText();
            city = cityField.getText();
            cnic = format1.getText();
            date=date1.getSelectedItem().toString();
            month=month1.getSelectedItem().toString();
            year=year1.getSelectedItem().toString();
            dob = date+"-" + month+"-" +year;
            // here i create the random card number...
            Random rand= new Random();
           int n= rand.nextInt(10000000) + (100000) ;
            System.out.println(n);
            flag = button1.isSelected();
            if (flag == true) {
                gender = "male";
            } else {
                gender = "female";
            }
            value = button3.isSelected();
            if (value == true) {
                status = "single";
            } else {
                status = "married";
            }
            GeneralDAO g = new GeneralDAO();
            boolean a = g.registration(name, f_name,cnic,email,dob,gender,status,pin,city,state,address,n);
            if (a==true) {
               // display message successfully sign up...
               JOptionPane.showMessageDialog(null,"Your Card Number is :"+ n,"Automated Teller Machine",JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        signin in = new signin();
        in.setVisible(true);
        in.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton button1;
    private javax.swing.JRadioButton button2;
    private javax.swing.JRadioButton button3;
    private javax.swing.JRadioButton button4;
    private javax.swing.JTextField cityField;
    private javax.swing.JComboBox<String> date1;
    private javax.swing.JTextField field1;
    private javax.swing.JTextField field2;
    private javax.swing.JTextField field3;
    private javax.swing.JTextField field5;
    private javax.swing.JTextField field7;
    private javax.swing.JFormattedTextField format1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> month1;
    private javax.swing.ButtonGroup myButton;
    private javax.swing.ButtonGroup myGroup;
    private javax.swing.JPasswordField password1;
    private javax.swing.JComboBox<String> year1;
    // End of variables declaration//GEN-END:variables
}
